// swift-tools-version:5.5
import PackageDescription

let package = Package(
    name: "GPUImage",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v12),
        .macOS(.v10_15)
    ],
    products: [
        .library(
            name: "GPUImage",
            targets: ["GPUImage"]
        ),
    ],
    dependencies: [
        // No external dependencies
    ],
    targets: [
        .target(
            name: "GPUImage",
            path: "framework",
          
            sources: [
                "Source_iOS/GPUImageContext.m",
                "Source_iOS/GPUImageMovieWriter.m",
                "Source_iOS/GPUImagePicture+TextureSubimage.m",
                "Source_iOS/GPUImagePicture.m",
                "Source_iOS/GPUImageView.m",
                "Source/GLProgram.m",

                "Source/GPUImage3x3ConvolutionFilter.m",
                "Source/GPUImage3x3TextureSamplingFilter.m",
                "Source/GPUImageAdaptiveThresholdFilter.m",
                "Source/GPUImageAddBlendFilter.m",
                "Source/GPUImageAlphaBlendFilter.m",
                "Source/GPUImageAmatorkaFilter.m",
                "Source/GPUImageAmericaFilter.m",
                "Source/GPUImageAmerikanaFilter.m",
                "Source/GPUImageAndyFilter.m",
                "Source/GPUImageAverageColor.m",
                "Source/GPUImageAverageLuminanceThresholdFilter.m",
                "Source/GPUImageBilateralFilter.m",
                "Source/GPUImageBoxBlurFilter.m",
                "Source/GPUImageBrightnessFilter.m",
                "Source/GPUImageBuffer.m",
                "Source/GPUImageBulgeDistortionFilter.m",
                "Source/GPUImageCGAColorspaceFilter.m",
                "Source/GPUImageCannyEdgeDetectionFilter.m",
                "Source/GPUImageChromaKeyBlendFilter.m",
                "Source/GPUImageChromaKeyFilter.m",
                "Source/GPUImageClosingFilter.m",
                "Source/GPUImageColorBlendFilter.m",
                "Source/GPUImageColorBurnBlendFilter.m",
                "Source/GPUImageColorConversion.m",
                "Source/GPUImageColorDodgeBlendFilter.m",
                "Source/GPUImageColorInvertFilter.m",
                "Source/GPUImageColorLocalBinaryPatternFilter.m",
                "Source/GPUImageColorMatrixFilter.m",
                "Source/GPUImageColorPackingFilter.m",
                "Source/GPUImageColourFASTFeatureDetector.m",
                "Source/GPUImageColourFASTSamplingOperation.m",
                "Source/GPUImageContrastFilter.m",
                "Source/GPUImageCropFilter.m",
                "Source/GPUImageCrosshairGenerator.m",
                "Source/GPUImageCrosshatchFilter.m",
                "Source/GPUImageDarkenBlendFilter.m",
                "Source/GPUImageDifferenceBlendFilter.m",
                "Source/GPUImageDilationFilter.m",
                "Source/GPUImageDirectionalNonMaximumSuppressionFilter.m",
                "Source/GPUImageDirectionalSobelEdgeDetectionFilter.m",
                "Source/GPUImageDissolveBlendFilter.m",
                "Source/GPUImageDivideBlendFilter.m",
                "Source/GPUImageEmbossFilter.m",
                "Source/GPUImageErosionFilter.m",
                "Source/GPUImageExclusionBlendFilter.m",
                "Source/GPUImageExposureFilter.m",
                "Source/GPUImageFASTCornerDetectionFilter.m",
                "Source/GPUImageFalseColorFilter.m",
                "Source/GPUImageFilter.m",
                "Source/GPUImageFilterGroup.m",
                "Source/GPUImageFilterPipeline.m",
                "Source/GPUImageFourInputFilter.m",
                "Source/GPUImageFramebuffer.m",
                "Source/GPUImageFramebufferCache.m",
                "Source/GPUImageGammaFilter.m",
                "Source/GPUImageGaussianBlurFilter.m",
                "Source/GPUImageGaussianBlurPositionFilter.m",
                "Source/GPUImageGaussianSelectiveBlurFilter.m",
                "Source/GPUImageGlassSphereFilter.m",
                "Source/GPUImageGrayscaleFilter.m",
                "Source/GPUImageHSBFilter.m",
                "Source/GPUImageHalftoneFilter.m",
                "Source/GPUImageHardLightBlendFilter.m",
                "Source/GPUImageHarrisCornerDetectionFilter.m",
                "Source/GPUImageHazeFilter.m",
                "Source/GPUImageHighPassFilter.m",
                "Source/GPUImageHighlightShadowFilter.m",
                "Source/GPUImageHighlightShadowTintFilter.m",
                "Source/GPUImageHistogramEqualizationFilter.m",
                "Source/GPUImageHistogramFilter.m",
                "Source/GPUImageHistogramGenerator.m",
                "Source/GPUImageHoughTransformLineDetector.m",
                "Source/GPUImageHueBlendFilter.m",
                "Source/GPUImageHueFilter.m",
                "Source/GPUImageJFAVoronoiFilter.m",
                "Source/GPUImageKuwaharaFilter.m",
                "Source/GPUImageKuwaharaRadius3Filter.m",
                "Source/GPUImageLanczosResamplingFilter.m",
                "Source/GPUImageLaplacianFilter.m",
                "Source/GPUImageLevelsFilter.m",
                "Source/GPUImageLightenBlendFilter.m",
                "Source/GPUImageLineGenerator.m",
                "Source/GPUImageLinearBurnBlendFilter.m",
                "Source/GPUImageLocalBinaryPatternFilter.m",
                "Source/GPUImageLookupFilter.m",
                "Source/GPUImageLowPassFilter.m",
                "Source/GPUImageLuminanceRangeFilter.m",
                "Source/GPUImageLuminanceThresholdFilter.m",
                "Source/GPUImageLuminosity.m",
                "Source/GPUImageLuminosityBlendFilter.m",
                "Source/GPUImageMaskFilter.m",
                "Source/GPUImageMedianFilter.m",
                "Source/GPUImageMissEtikateFilter.m",
                "Source/GPUImageMonochromeFilter.m",
                "Source/GPUImageMosaicFilter.m",
                "Source/GPUImageMotionBlurFilter.m",
                "Source/GPUImageMotionDetector.m",
                "Source/GPUImageMovie.m",
                "Source/GPUImageMovieComposition.m",
                "Source/GPUImageMultiplyBlendFilter.m",
                "Source/GPUImageNobleCornerDetectionFilter.m",
                "Source/GPUImageNonMaximumSuppressionFilter.m",
                "Source/GPUImageNormalBlendFilter.m",
                "Source/GPUImageOpacityFilter.m",
                "Source/GPUImageOpeningFilter.m",
                "Source/GPUImageOutput.m",
                "Source/GPUImageOverlayBlendFilter.m",
                "Source/GPUImageParallelCoordinateLineTransformFilter.m",
                "Source/GPUImagePerlinNoiseFilter.m",
                "Source/GPUImagePinchDistortionFilter.m",
                "Source/GPUImagePixellateFilter.m",
                "Source/GPUImagePixellatePositionFilter.m",
                "Source/GPUImagePoissonBlendFilter.m",
                "Source/GPUImagePolarPixellateFilter.m",
                "Source/GPUImagePolkaDotFilter.m",
                "Source/GPUImagePosterizeFilter.m",
                "Source/GPUImagePrewittEdgeDetectionFilter.m",
                "Source/GPUImageRGBClosingFilter.m",
                "Source/GPUImageRGBDilationFilter.m",
                "Source/GPUImageRGBErosionFilter.m",
                "Source/GPUImageRGBFilter.m",
                "Source/GPUImageRGBOpeningFilter.m",
                "Source/GPUImageRawDataInput.m",
                "Source/GPUImageRawDataOutput.m",
                "Source/GPUImageSaturationBlendFilter.m",
                "Source/GPUImageSaturationFilter.m",
                "Source/GPUImageScreenBlendFilter.m",
                "Source/GPUImageSepiaFilter.m",
                "Source/GPUImageSharpenFilter.m",
                "Source/GPUImageShiTomasiFeatureDetectionFilter.m",
                "Source/GPUImageSingleComponentGaussianBlurFilter.m",
                "Source/GPUImageSketchFilter.m",
                "Source/GPUImageSkinToneFilter.m",
                "Source/GPUImageSmoothToonFilter.m",
                "Source/GPUImageSobelEdgeDetectionFilter.m",
                "Source/GPUImageSoftEleganceFilter.m",
                "Source/GPUImageSoftLightBlendFilter.m",
                "Source/GPUImageSolarizeFilter.m",
                "Source/GPUImageSolidColorGenerator.m",
                "Source/GPUImageSourceOverBlendFilter.m",
                "Source/GPUImageSphereRefractionFilter.m",
                "Source/GPUImageStillCamera.m",
                "Source/GPUImageStretchDistortionFilter.m",
                "Source/GPUImageSubtractBlendFilter.m",
                "Source/GPUImageSwirlFilter.m",
                "Source/GPUImageTextureInput.m",
                "Source/GPUImageTextureOutput.m",
                "Source/GPUImageThreeInputFilter.m",
                "Source/GPUImageThresholdEdgeDetectionFilter.m",
                "Source/GPUImageThresholdSketchFilter.m",
                "Source/GPUImageThresholdedNonMaximumSuppressionFilter.m",
                "Source/GPUImageTiltShiftFilter.m",
                "Source/GPUImageToneCurveFilter.m",
                "Source/GPUImageToonFilter.m",
                "Source/GPUImageTransformFilter.m",
                "Source/GPUImageTwoInputCrossTextureSamplingFilter.m",
                "Source/GPUImageTwoInputFilter.m",
                "Source/GPUImageTwoPassFilter.m",
                "Source/GPUImageTwoPassTextureSamplingFilter.m",
                "Source/GPUImageUIElement.m",
                "Source/GPUImageUnsharpMaskFilter.m",
                "Source/GPUImageVibranceFilter.m",
                "Source/GPUImageVideoCamera.m",
                "Source/GPUImageVignetteFilter.m",
                "Source/GPUImageVoronoiConsumerFilter.m",
                "Source/GPUImageWeakPixelInclusionFilter.m",
                "Source/GPUImageWhiteBalanceFilter.m",
                "Source/GPUImageXYDerivativeFilter.m",
                "Source/GPUImageZoomBlurFilter.m",
                "Source/GPUImageiOSBlurFilter.m"              
            ],
            resources: [
                .process("Resources/*.png")
            ],
            publicHeadersPath: "Source_iOS/Framework",
            cSettings: [
                .define("CLANG_MODULES_AUTOLINK", to: "YES"),
                .define("GCC_WARN_ABOUT_RETURN_TYPE", to: "YES"),
                .headerSearchPath("Source"),
                .headerSearchPath("Source_iOS"),
                .headerSearchPath("Source_iOS/Framework/GPUImage"),
                .unsafeFlags(["-fobjc-arc"]) // Enables ARC
            ],
            linkerSettings: [
                .linkedFramework("OpenGLES"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("AVFoundation")
            ]
        )
    ]
)
